// packages/vue/src/components/ui/MathCurveProgress.vue
<script setup lang="ts">
import { computed } from 'vue'
import { getPoint, getAngle, buildPath } from '@/lib/math-curves'
import type { ProgressCurveKey } from '@/lib/math-curves'

interface MathCurveProgressProps {
  value: number
  curve?: ProgressCurveKey
  size?: 'sm' | 'md' | 'lg'
  showValue?: boolean
  trackColor?: string
  fillColor?: string
  strokeWidth?: number
  class?: string
}

const props = withDefaults(defineProps<MathCurveProgressProps>(), {
  curve: 'spiral',
  size: 'md',
  showValue: false,
  strokeWidth: 4,
})

const sizeMap: Record<NonNullable<MathCurveProgressProps['size']>, number> = {
  sm: 48,
  md: 64,
  lg: 96,
}

const pixelSize = computed(() => sizeMap[props.size ?? 'md'])

const clampedValue = computed(() => Math.min(100, Math.max(0, props.value ?? 0)))

const trackPath = computed(() => buildPath(props.curve ?? 'spiral'))

const headPoint = computed(() => getPoint(props.curve ?? 'spiral', clampedValue.value / 100))

const headAngle = computed(() => getAngle(props.curve ?? 'spiral', clampedValue.value / 100))

const headTransform = computed(() => {
  const { x, y } = headPoint.value
  const angle = headAngle.value
  return `rotate(${angle} ${x} ${y})`
})

// Build the fill path: only draw up to value progress
const fillPath = computed(() => {
  const curve = props.curve ?? 'spiral'
  const progress = clampedValue.value / 100
  if (progress <= 0) return ''
  // Build a partial path by limiting segments proportionally
  const totalSegments = 200
  const segments = Math.max(1, Math.round(totalSegments * progress))
  let d = ''
  for (let i = 0; i <= segments; i++) {
    const p = (i / totalSegments) * progress
    const pt = getPoint(curve, p)
    if (i === 0) {
      d = `M ${pt.x.toFixed(2)} ${pt.y.toFixed(2)}`
    } else {
      d += ` L ${pt.x.toFixed(2)} ${pt.y.toFixed(2)}`
    }
  }
  return d
})
</script>

<template>
  <div
    :class="props.class"
    :style="{ width: pixelSize + 'px', height: pixelSize + 'px', position: 'relative', display: 'inline-block' }"
    role="progressbar"
    :aria-valuenow="clampedValue"
    aria-valuemin="0"
    aria-valuemax="100"
  >
    <svg
      :width="pixelSize"
      :height="pixelSize"
      viewBox="0 0 100 100"
      style="overflow: visible; display: block"
    >
      <!-- Track (full curve, low opacity) -->
      <path
        :d="trackPath"
        :stroke="trackColor ?? 'currentColor'"
        :stroke-width="strokeWidth"
        stroke-opacity="0.2"
        stroke-linecap="square"
        stroke-linejoin="miter"
        fill="none"
      />
      <!-- Fill (partial curve up to value) -->
      <path
        :d="fillPath"
        :stroke="fillColor ?? 'currentColor'"
        :stroke-width="strokeWidth"
        stroke-linecap="square"
        stroke-linejoin="miter"
        fill="none"
        style="transition: d 300ms ease"
      />
      <!-- Head rect -->
      <rect
        :width="strokeWidth * 2"
        :height="strokeWidth * 2"
        :x="headPoint.x - strokeWidth"
        :y="headPoint.y - strokeWidth"
        :fill="fillColor ?? 'currentColor'"
        :transform="headTransform"
        :style="{ transition: 'transform 300ms ease' }"
      />
    </svg>
    <!-- Optional value label -->
    <div
      v-if="showValue"
      style="
        position: absolute;
        inset: 0;
        display: flex;
        align-items: center;
        justify-content: center;
        font-weight: 700;
        font-size: 0.75em;
        pointer-events: none;
      "
    >
      {{ Math.round(clampedValue) }}%
    </div>
  </div>
</template>

// src/components/ui/math-curve-progress.tsx
import * as React from 'react'
import { cva, type VariantProps } from 'class-variance-authority'
import { cn } from '@/lib/utils'
import {
  buildPath,
  getPoint,
  getAngle,
  type ProgressCurveKey,
} from '@/lib/math-curves'

const mathCurveProgressVariants = cva('', {
  variants: {
    size: {
      sm: 'w-12 h-12',
      md: 'w-16 h-16',
      lg: 'w-24 h-24',
    },
  },
  defaultVariants: {
    size: 'md',
  },
})

export interface MathCurveProgressProps
  extends React.SVGAttributes<SVGSVGElement>,
    VariantProps<typeof mathCurveProgressVariants> {
  value: number
  curve?: ProgressCurveKey
  showValue?: boolean
  trackColor?: string
  fillColor?: string
  strokeWidth?: number
}

const MathCurveProgress = React.forwardRef<SVGSVGElement, MathCurveProgressProps>(
  (
    {
      className,
      size,
      value,
      curve = 'spiral',
      showValue = false,
      trackColor,
      fillColor,
      strokeWidth = 4,
      ...props
    },
    ref
  ) => {
    const clampedValue = Math.min(100, Math.max(0, value))
    const progress = clampedValue / 100

    const trackPath = React.useMemo(() => buildPath(curve, 1.0), [curve])
    const headPoint = React.useMemo(() => getPoint(curve, progress), [curve, progress])
    const headAngle = React.useMemo(() => getAngle(curve, progress), [curve, progress])
    const HEAD_SIZE = 8

    const resolvedTrackStroke = trackColor ?? 'currentColor'
    const resolvedFillColor = fillColor ?? 'hsl(var(--primary))'

    return (
      <svg
        ref={ref}
        viewBox="0 0 100 100"
        xmlns="http://www.w3.org/2000/svg"
        role="progressbar"
        aria-valuenow={clampedValue}
        aria-valuemin={0}
        aria-valuemax={100}
        aria-label={`${Math.round(clampedValue)}% progress`}
        className={cn(mathCurveProgressVariants({ size }), className)}
        {...props}
      >
        {/* Track layer */}
        <path
          d={trackPath}
          fill="none"
          stroke={resolvedTrackStroke}
          strokeWidth={strokeWidth}
          strokeOpacity={0.2}
          strokeLinecap="square"
          strokeLinejoin="miter"
        />
        {/* Head square — CSS transition for smooth value-driven movement */}
        <rect
          width={HEAD_SIZE}
          height={HEAD_SIZE}
          x={headPoint.x - HEAD_SIZE / 2}
          y={headPoint.y - HEAD_SIZE / 2}
          fill={resolvedFillColor}
          stroke="currentColor"
          strokeWidth={1.5}
          transform={`rotate(${headAngle} ${headPoint.x} ${headPoint.y})`}
          style={{ transition: 'transform 300ms ease' }}
        />
        {/* Optional numeric label */}
        {showValue && (
          <text
            x={50}
            y={50}
            textAnchor="middle"
            dominantBaseline="central"
            fontSize={12}
            fontWeight={700}
            fill="currentColor"
            letterSpacing="0.05em"
            style={{ userSelect: 'none', fontFamily: 'inherit' }}
          >
            {Math.round(clampedValue)}%
          </text>
        )}
      </svg>
    )
  }
)
MathCurveProgress.displayName = 'MathCurveProgress'

export { MathCurveProgress, mathCurveProgressVariants }
